//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trindl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hakkimizda
    {
        public int ID { get; set; }
        public string Resim { get; set; }
        public string Aciklama_tr { get; set; }
        public string Aciklama_en { get; set; }
        public string Aciklama_de { get; set; }
    }
}
