//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trindl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sabitler
    {
        public int SabitID { get; set; }
        public string Baslik_tr { get; set; }
        public string Baslik_en { get; set; }
        public string Baslik_de { get; set; }
        public string DegisenYazi_tr { get; set; }
        public string DegisenYazi_en { get; set; }
        public string DegisenYazi_de { get; set; }
        public string Instagram { get; set; }
        public string Facebook { get; set; }
        public string Youtube { get; set; }
        public string VideoLink { get; set; }
        public string Adres { get; set; }
        public string Telefon_tr { get; set; }
        public string Telefon_de { get; set; }
        public string Whatsapp { get; set; }
    }
}
