//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trindl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunlerView
    {
        public int UrunID { get; set; }
        public string UrunAdi_tr { get; set; }
        public string UrunAdi_en { get; set; }
        public string UrunAdi_de { get; set; }
        public string UrunAciklama_tr { get; set; }
        public string UrunAciklama_en { get; set; }
        public string UrunAciklama_de { get; set; }
        public string UrunResim { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public string KategoriAdi_tr { get; set; }
        public string KategoriAdi_en { get; set; }
        public string KategoriAdi_de { get; set; }
        public string OneCikarilsinMi { get; set; }
    }
}
